### PR TITLE
change name of package to sitrep

### LINKED ISSUE #31: Rename package to "sitrep"
As discussed in #11

### PR DESCRIPTION
**Pull request by zkamvar**
This will fix #31 

 - change DESCRIPTION
 - Change Rproj file (there were two for some reason)
 - update tests/testhat.R
 - update README

### CODE REVIEW

**Comment by dirkschumacher** [comment]
Thanks, can you rename `epireports.Rproj` instead of deleting it?

**Comment by dirkschumacher** [comment]
Apart from that. Looks good to me :shipit:

**Comment by zkamvar** [comment]
> Thanks, can you rename `epireports.Rproj` instead of deleting it?

If you look closely, that's what I did. There were two .Rproj files for some reason. I changed the r4epi.Rproj file because it was more specific.

**Comment by dirkschumacher** [comment]
> > Thanks, can you rename `epireports.Rproj` instead of deleting it?
> 
> If you look closely, that's what I did. There were two .Rproj files for some reason. I changed the r4epi.Rproj file because it was more specific.

Sorry. Allright Ship it. Ship it good! https://youtu.be/fK8mneO8yvU?t=13

**Pull request merged**
