### PR TITLE
switch to epibuffet; remove outbreaks; add gha

### LINKED ISSUE #229: basic univariate analysis package
This should encompass the following functions:

 - `tab_univariate()` 
 - `data_frame_from_2x2()`
 
I will also need to add more tests and address the issue where it currently only accepts TRUE/FALSE for strata variables, when strata could be any binary variable. I should also make it so that it can accept 1/0 data (as is not uncommon)

### PR DESCRIPTION
**Pull request by zkamvar**
This will fix #229 by combining #266 and #234 with the current master version of the repo. 

I'm also adding in github actions here so that we auto-build the documentation site and contain the checks on GitHub so that we don't have to worry about failing checks on Travis or Appveyor.

### CODE REVIEW

**Comment by zkamvar** [comment]
Note: I do not expect the appveyor or travis checks to pass because they were notoriously problematic

**Comment by zkamvar** [comment]
Additionally, once https://github.com/R4EPI/epibuffet/pull/16 and https://github.com/R4EPI/epikit/pull/21 are merged, then we can remove the branches from the Remotes field

**Comment by zkamvar** [comment]
They have been merged and epikit is on CRAN, so things are good to go

**Review by aspina7 — APPROVED** [review]
looks good

**Pull request merged**
