### PR TITLE
generate dummy data for mortality survey - far away from perfect

### PR DESCRIPTION
**Pull request by lukric**
Updated gen_data() function to also support dummy data for the mortality survey. magrittr and tidyselect added to imports (used in msf_dict_mortality() - a non-exported function to accordingly tidy msf dictionary for mortality surveys)

The data.frame which is created from gen_data(disease = "mortality") may not be fully logical, but should fulfill the purpose for testing the survey template.

### CODE REVIEW

**Comment by zkamvar** [comment]
Hi @lukric, welcome aboard!

I would request keeping survey data and disease data generation as separate functions. My recommendation for this is:

 1. make `gen_data()` a genearlized function that will pass arguments to either the survey or disease data generating functions
 2. move the current `gen_data()` function to `gen_disease_data()` and `gen_survey_data()`.

**Comment by lukric** [comment]
hey @zkamvar, thanks!

I thought about this. `gen_disease_data()` and `gen_survey_data()` share almost all code (I translated the mortality dictionary in a way that @aspina7`s `gen_data()` can deal with it.

If we want to seperate `gen_disease_data()` and `gen_survey_data()` we also need to make most of the `gen_data()` some sort of a helper function. Is that OK? Further we should rename the `disease` variable name of `gen_data()` @aspina7 ?

After my pull request Alex told me to avoid the pipe operator, will also take care of that later today.

**Comment by zkamvar** [comment]
> hey @zkamvar, thanks!
> 
> I thought about this. `gen_disease_data()` and `gen_survey_data()` share almost all code (I translated the mortality dictionary in a way that @aspina7's `gen_data()` can deal with it.
> 
> If we want to seperate `gen_disease_data()` and `gen_survey_data()` we also need to make most of the `gen_data()` some sort of a helper function. Is that OK? Further we should rename the `disease` variable name of `gen_data()` @aspina7 ?

Good point! In this case, it may be better just to leave things as they are and just rename the `disease` variable name.

> After my pull request Alex told me to avoid the pipe operator, will also take care of that later today.

Yeah, the pipe operator is great for analysis, but not so good for packages. Remove it if you can.

**Comment by aspina7** [comment]
yeap think we are alright just having one function to churn fake dictionaries out. Would be good to keep the **dictionary** functions seperate for outbreak and survey though - because survey will probably grow quite complex. Going to be changing between three different data input softwares in long run... 
But just roll with what we have for now

**Pull request closed without merging**
