### PR TITLE
Tidyr cols update

### LINKED ISSUE #202: surveys::descriptive_sampling_bias chunk
descriptive_sampling_bias gives this warning, unsure if we can ignore (for the moment have set chunks to warning = FALSE in mortality and vaccintion)

```
Warning message:
`cols` is now required.
Please use `cols = c(binom)` 
```

### PR DESCRIPTION
**Pull request by aspina7**
this will fix #202

### CODE REVIEW

**Comment by zkamvar** [comment]
> will also need to add this to the univariate example on the website

I already did that when I saw that you had used `pivot_wider()`

**Comment by zkamvar** [comment]
Note: this will close #202

**Comment by zkamvar** [comment]
Also, Travis is only failing for some weird configuration booboo on MacOS, so it's good to go

**Comment by aspina7** [comment]
https://gph.is/g/ZYA82L1

**Pull request merged**
