### PR TITLE
Pretty age pyramid

### PR DESCRIPTION
**Pull request by zkamvar**
This addresses one of the comments brought up in #64. 

 - adds vertical line to the plot
 - removes left-hand bar and adds dashed lines for the age groups
 - allows another color through the option `stack_by` (which defaults to `split_by`)

Request any other mods on this PR

image

### CODE REVIEW

**Comment by aspina7** [comment]
This looks awesome. Can we also add text labels either side of the vertical divider to show male/female (or whatever the grouper is) please?

**Comment by zkamvar** [comment]
> This looks awesome. Can we also add text labels either side of the vertical divider to show male/female (or whatever the grouper is) please?

[Grouper, you say?](https://www.youtube.com/watch?v=GJgXdSVFnJE).

Seriously, though, I think it's certainly possible. I'll get to it on Monday

**Comment by pbkeating** [comment]
This looks great!!

**Comment by aspina7** [comment]
mmmm can we have the option to turn off the text labels on top if its not stacked please? (otherwise legend and text seems overkill) 
Also option to turn off the lines?
.... pedantic ... so if short on time just merge and we can address at a later stage

**Comment by zkamvar** [comment]
> mmmm can we have the option to turn off the text labels on top if its not stacked please? (otherwise legend and text seems overkill)
> Also option to turn off the lines?
> .... pedantic ... so if short on time just merge and we can address at a later stage

Those options should be fairly straightforward. I'll give em a go and be back in 10

**Comment by zkamvar** [comment]
``` r
library(ggplot2)
library(sitrep)
set.seed(2018-01-15)
ages <- cut(sample(80, 150, replace = TRUE),
            breaks = c(0, 5, 10, 30, 90), right = FALSE)
sex  <- sample(c("Female", "Male"), 150, replace = TRUE)
ill  <- sample(c("case", "non-case"), 150, replace = TRUE)
dat  <- data.frame(AGE = ages, sex = sex, ill = ill, stringsAsFactors = FALSE)

# Create the age pyramid, stratifying by sex
print(ap   <- plot_age_pyramid(dat, age_group = "AGE"))
#> Warning: Removed 2 rows containing missing values (position_stack).
```



``` r
# Stratify by case definition and customize with ggplot2
ap   <- plot_age_pyramid(dat, age_group = "AGE", split_by = "ill") +
  theme_bw(base_size = 16) +
  labs(title = "Age groups by case definition")
print(ap)
#> Warning: Removed 2 rows containing missing values (position_stack).
```



``` r

# Stratify by multiple factors
ap   <- plot_age_pyramid(dat, 
                         age_group = "AGE", 
                         split_by = "sex", 
                         stack_by = "ill",
                         vertical_lines = TRUE,
                         horizontal_lines = FALSE) +
  labs(title = "Age groups by case definition and sex")
print(ap)
#> Warning: Removed 4 rows containing missing values (position_stack).
#> Warning: Removed 2 rows containing missing values (geom_bar).
```



<sup>Created on 2019-02-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by zkamvar** [comment]
If it's to your liking, merge

**Comment by aspina7** [comment]
Perfect!

**Pull request merged**
