### PR TITLE
goddam tidyverse

### PR DESCRIPTION
**Pull request by aspina7**
@zkamvar trying to mess around with the whole adding AR and CFR to a plot with case counts... 
tidyverse doesnt like two y axes.... hence the mess that ive painted... 
any wizardy ideas?

### CODE REVIEW

**Comment by aspina7** [comment]
image

**Comment by zkamvar** [comment]
> @zkamvar trying to mess around with the whole adding AR and CFR to a plot with case counts...
> tidyverse doesnt like two y axes.... hence the mess that ive painted...
> any wizardy ideas?

There's a good reason why tidyverse doesn't allow two y-axes: they can be severely misleading. 

Moreover, you placed both CFR and AR on the same graph, which hides the CFR since AR's upper limit is 100x larger than CFR. I came up with a solution using cowplot:

image


Also, I've added `merge_ci_df()` to some of the pipes to put the CI in parens

**Comment by aspina7** [comment]
i know its bad practice ... but also dont think they should be the fashion police

**Comment by zkamvar** [comment]
> i know its bad practice ... but also dont think they should be the fashion police

**Comment by zkamvar** [comment]
I'm cool with merging this if you want it merged

**Comment by aspina7** [comment]
yap just taking a quick look then will merge

**Comment by zkamvar** [comment]
FWIW: There IS a way to do the dual-axes thing with cowplot:

https://rdrr.io/cran/cowplot/man/align_plots.html

**Comment by aspina7** [comment]
hey zhian  - added a bunch of stuff but is super messy as per usual - but all kinda half works... 
gen_polygon seems to add lat and long lines but cant work out why, might be because of add grid but doesnt match the grid so doesnt really make sense. 
in the epiweek forloop i guess need to add the bit on completing for empties, but too tired to figure out right now.

**Comment by zkamvar** [comment]
> gen_polygon seems to add lat and long lines but cant work out why, might be because of add grid but doesnt match the grid so doesnt really make sense.

I don't think it's adding lat/long lines... those are the group divisions:

``` r
ggplot2::ggplot() + ggplot2::geom_sf(data = sitrep::gen_polygon(letters[1:10]))
```



```r
ggplot2::ggplot() + ggplot2::geom_sf(data = sitrep::gen_polygon(letters[1:2]))
```


<sup>Created on 2019-02-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by zkamvar** [comment]
I changed the mapping so that it now creates a square grid by taking the ceiling of the square root of the number of regions and using those for nx and ny

image

**Comment by aspina7** [comment]
gonna merge this for now - can reopen later if need to make more edits

**Comment by zkamvar** [comment]
Awesome!

**Pull request merged**
