### PR TITLE
Znk better age pyramid

### PR DESCRIPTION
**Pull request by zkamvar**
I've updated the age pyramid function so that it will always display a pyramid, with the first group in the `split_by` factor being shoved to the left side unless the user specifically changes it with the `compare_group` option. This will also automatically highlight missing data unless the user specifies `na.rm = TRUE` and then it will warn the user that it is removing missing data across which columns. 

``` r
  library("tidyverse")
  library("sitrep")
set.seed(2018-01-15)
ages <- cut(sample(80, 150, replace = TRUE),
           breaks = c(0, 5, 10, 30, 50, 80, 100), right = FALSE)
sex  <- sample(c("Female", "Male"), 150, replace = TRUE)
gender <- sex
gender[sample(5)] <- "NB"
ill  <- sample(0:1, 150, replace = TRUE)
dat  <- data.frame(AGE             = ages,
                  sex              = factor(sex, c("Male", "Female")),
                  gender           = factor(gender, c("Male", "NB", "Female")),
                  ill              = ill,
                  stringsAsFactors = FALSE)
print(ap1  <- plot_age_pyramid(dat, age_group = AGE))
```

``` r
# will create facetted pyramids by default
print(ap2  <- plot_age_pyramid(dat, age_group = AGE, split_by = gender))
```

``` r
# gives the user the option to stack instead of facet
print(ap2  <- plot_age_pyramid(dat, age_group = AGE, split_by = gender, facet = FALSE))
```

``` r
# can also switch which group to compare against
print(ap2  <- plot_age_pyramid(dat, age_group = AGE, split_by = gender, compare_group = "Female"))
```

<sup>Created on 2019-09-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### CODE REVIEW

**Comment by zkamvar** [comment]
> hmmmm on second thought, not sure the facet adds much. Because it is pretty much just showing the same thing twice, with the plotting order and colouring changed, no?

Not exactly. It's fixing one group to the left and comparing the other groups alongside while showing the entire distribution of the data as a shadow bar underneath. 

For context, this was an updated solution to #130, which dropped the pyramid structure if there were more than two categories (which @kdoyle514 had issues with).

age


> Maybe better off just splitting the NB in half, and plotting at bottom of bar eitherside.

This solution is meant to be a general solution, not just for three categories, so this wouldn't work exactly. Additionally, it would be difficult to interpret this because you will end up creating half a person if the number of NB is odd. 

> This way both male and female are shifted out an equal amount, so can still directly compare the overall structure - while also seeing the distribution of missings.

1. NB is not 'missing' in this case. It is a third category
2. The point is that you are still comparing the overall structure. The filled bars show you the counts for the defined categories and the transparent bars underneath show you the part of the population that don't fit into those categories.

> And if age group is missing then that is plotted as a seperate category at top of y-axis?

Yup. This is correct

> Maybe this is just non-solvable, cus then what happens if we chuck in a third variable like case definition....

So pessimistic this one. We solved this:

``` r
library("tidyverse")
library("sitrep")
set.seed(2018-01-15)
ages <- cut(sample(80, 150, replace = TRUE),
           breaks = c(0, 5, 10, 30, 50, 80, 100), right = FALSE)
sex  <- sample(c("Female", "Male"), 150, replace = TRUE)
gender <- sex
gender[sample(5)] <- "NB"
ill  <- sample(0:1, 150, replace = TRUE)
dat  <- data.frame(AGE             = ages,
                  sex              = factor(sex, c("Male", "Female")),
                  gender           = factor(gender, c("Male", "NB", "Female")),
                  ill              = ill,
                  stringsAsFactors = FALSE)
print(ap1  <- plot_age_pyramid(dat, age_group = AGE, split_by = "gender", stack_by = ill, pal = c(`0` = "powderblue", `1` = "forestgreen")))
```



<sup>Created on 2019-09-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

> 
> kinda feel the last iteration with facetted bars seperately did the best of the tricks?
:man_shrugging:

**Comment by kdoyle514** [comment]
I think in most MSF settings, the expected behavior with an age pyramid is to always create one comparing only males and females. I worry that if there's an "Unknown" or something category that people haven't NA'd out, they get an output they don't expect and don't know how to fix. I recognize this is problematic and excludes people outside the gender binary. (Though three options doesn't really fix that either.) Would it be possible to have an explicit option to create the different reference group facets?

I am pitting my desire for inclusion versus field needs here and am not super comfortable with the latter. Also not sure how much of an issue it would be. Maybe @epiamsterdam can weigh in?

**Comment by epiamsterdam** [comment]
I would like to keep default solution of 3 bars next to eachother.

The compare option is fine as a seperate option is fine but we shouldnt spend more time on it.

**Comment by zkamvar** [comment]
> I think in most MSF settings, the expected behavior with an age pyramid is to always create one comparing only males and females. I worry that if there's an "Unknown" or something category that people haven't NA'd out, they get an output they don't expect and don't know how to fix. I recognize this is problematic and excludes people outside the gender binary. (Though three options doesn't really fix that either.) Would it be possible to have an explicit option to create the different reference group facets?

Can you explain what you mean by "have an explicit option to create the different reference group facets"? I don't know what you mean by "reference group facets". I'm cool to skype on this if need be
 
> I am pitting my desire for inclusion versus field needs here and am not super comfortable with the latter. Also not sure how much of an issue it would be. Maybe @epiamsterdam can weigh in?

I think you are correct in terms of having field needs first since you are going to have exhausted field epis looking at this. In the MSF setting I think we would encounter three situations:

1. The field epi only has two categories in their data, they will get a pyramid and everything will be hunky-dory
2. The field epi has missing data (explicit or implicit) 
3. There are two categories, but some are misspelled and mis-interpreted as > 2 categories

For 1, everything is fine and they will get a pyramid with the current and new code.

For 2 and 3, with the current code, they get facetted bar plots (as shown in #130), but with the new code, they will get facetted pyramids, with one group always on the left side of the split. 

The question is: what *should* happen for 2 and 3? @kdoyle514 @aspina7 @epiamsterdam 

The challenges for this question:

i. we don't necessarily know which categories are males and females
ii. how do we alert the epi to missing data?
iii. how do we alert the epi to misspellings?

**Comment by zkamvar** [comment]
> Tough three options doesn't really fix that either.

Clarification: this is meant to be generalizeable to any number of categories.

**Comment by epiamsterdam** [comment]
Hi guys. Even though I understand we havent fully resolved this - I do think the current solution/function will work for our current needs (and majority of those needs) in the field.
Lets take note of the issue that it requires a bit more conversation and possible new functions. 
But for now, I would prefer that none of you (@zkamvar @kdoyle514 @aspina7 ) spend more time on this.

**Pull request closed without merging**
