### PR TITLE
update proportion functions

### PR DESCRIPTION
**Pull request by zkamvar**
This updates the proportion functions in the following way

 - lose the `digits` argument
 - no longer round their output
 - now have documentation
 - now have tests
 - Outbreak template uses `knitr::kable(digits = 2)`
 - markdown is now used for documentation

### CODE REVIEW

**Comment by dirkschumacher** [comment]
LGTM

**Comment by zkamvar** [comment]
I would like to get @aspina7's comments since this affects code he has added (RE #40)

**Comment by aspina7** [comment]
yap am happy with it too based on your prev reasoning!

**Comment by zkamvar** [comment]
Okay, I will merge this!

**Pull request merged**
